const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a comprehensive Multi-page PDF Report utilizing pdfkit.
 */
function generateTaxReportPDF(reportData, companyDetails) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });

            // For saving temporarily to local disk.
            // In a real prod environment, this would be streamed to S3 or Blob Storage
            const reportDir = path.join(__dirname, '../public/reports');
            if (!fs.existsSync(reportDir)) {
                fs.mkdirSync(reportDir, { recursive: true });
            }

            const fileName = `TaxReport_${reportData.reportId}_${Date.now()}.pdf`;
            const filePath = path.join(reportDir, fileName);
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // ================== SECTION 1: COVER PAGE ==================
            doc.fontSize(24).text('SmartTax Comprehensive Report', { align: 'center' });
            doc.moveDown(1);

            doc.fontSize(14).text(`Tax Year: ${reportData.taxYear || '2024-2025'}`, { align: 'center' });
            doc.text(`Company Name: ${companyDetails.name}`, { align: 'center' });
            if (companyDetails.taxId) doc.text(`Registration/Tax ID: ${companyDetails.taxId}`, { align: 'center' });
            doc.text(`Report ID: ${reportData.reportId}`, { align: 'center' });
            doc.text(`Regime Selected: ${reportData.regimeSelected}`, { align: 'center' });

            doc.moveDown(3);
            doc.fontSize(12).text('Generated by SmartTax Enterprise System', { align: 'center', color: 'grey' });
            doc.text(`Timestamp: ${new Date().toISOString()}`, { align: 'center', color: 'grey' });

            doc.addPage();

            // ================== SECTION 2: EXECUTIVE SUMMARY ==================
            doc.fillColor('black');
            doc.fontSize(18).text('Executive Summary', { underline: true });
            doc.moveDown(1);

            doc.fontSize(12).text(`Gross Revenue: $${reportData.financialSummary.grossRevenue.toFixed(2)}`);
            doc.text(`Total Expenses: $${reportData.financialSummary.totalExpenses.toFixed(2)}`);
            doc.text(`Total Deductions: $${reportData.financialSummary.totalDeductions.toFixed(2)}`);

            doc.moveDown(0.5);
            doc.text(`Taxable Income: $${reportData.financialSummary.taxableIncome.toFixed(2)}`, { stroke: true });

            doc.moveDown(1);
            doc.text(`Base Tax: $${reportData.financialSummary.baseTax.toFixed(2)}`);
            doc.text(`Surcharge Applied: $${reportData.financialSummary.surchargeAppied.toFixed(2)}`);
            doc.text(`Cess Applied: $${reportData.financialSummary.cessApplied.toFixed(2)}`);

            doc.moveDown(0.5);
            doc.fontSize(14).text(`Total Tax Liability: $${reportData.financialSummary.totalTax.toFixed(2)}`, { stroke: true });
            doc.text(`Net Payable (After Credits): $${reportData.financialSummary.netPayable.toFixed(2)}`);
            doc.text(`Effective Tax Rate: ${reportData.financialSummary.effectiveRate.toFixed(2)}%`);

            doc.addPage();

            // ================== SECTION 3: SLAB BREAKDOWN ==================
            doc.fontSize(18).text('Slab-Level Tax Calculation', { underline: true });
            doc.moveDown(1);

            if (reportData.financialSummary.slabBreakdown && reportData.financialSummary.slabBreakdown.length > 0) {
                const tableTop = doc.y;
                let currentY = tableTop;

                // Table Headers
                doc.fontSize(10);
                doc.text('Income Range', 50, currentY, { width: 150 });
                doc.text('Rate (%)', 200, currentY, { width: 100 });
                doc.text('Amount Taxed', 300, currentY, { width: 100 });
                doc.text('Tax ($)', 400, currentY, { width: 100 });

                doc.moveTo(50, currentY + 15).lineTo(500, currentY + 15).stroke();

                currentY += 25;

                // Table Rows
                for (const slab of reportData.financialSummary.slabBreakdown) {
                    doc.text(slab.range, 50, currentY, { width: 150 });
                    doc.text((slab.rate * 100).toFixed(2), 200, currentY, { width: 100 });
                    doc.text(slab.amountTaxed.toFixed(2), 300, currentY, { width: 100 });
                    doc.text(slab.tax.toFixed(2), 400, currentY, { width: 100 });
                    currentY += 20;
                }
            } else {
                doc.fontSize(12).text('No slab breakdown available (likely a flat rate tax).');
            }

            doc.addPage();

            // ================== SECTION 4: DEDUCTIONS SUMMARY ==================
            doc.fontSize(18).text('Deductions Breakdown & Validation', { underline: true });
            doc.moveDown(1);

            if (reportData.financialSummary.validatedDeductions && reportData.financialSummary.validatedDeductions.length > 0) {
                for (const deduction of reportData.financialSummary.validatedDeductions) {
                    doc.fontSize(12).fillColor('black').text(`Type: ${deduction.type}`);
                    doc.fontSize(10).text(`Claimed: $${deduction.claimed.toFixed(2)}`);
                    doc.text(`Allowed: $${deduction.allowed.toFixed(2)}`);
                    if (deduction.rejected > 0) {
                        doc.fillColor('red').text(`Rejected: $${deduction.rejected.toFixed(2)} | Reason: ${deduction.reason}`);
                    } else {
                        doc.fillColor('green').text(`Status: ${deduction.reason}`);
                    }
                    doc.moveDown(1);
                }
            } else {
                doc.fillColor('black').fontSize(12).text('No deductions claimed or applicable.');
            }

            // Finalizing
            doc.addPage();
            doc.fillColor('black').fontSize(14).text('Compliance Summary & Signatures', { underline: true });
            doc.moveDown(1);
            doc.fontSize(10).text('This document serves as proof of computed tax liability under the selected tax regime.');
            doc.text('System Integrity Hash (SHA-256):');
            doc.fontSize(8).text(reportData.reportHash, { color: 'grey' });

            doc.end();

            stream.on('finish', () => {
                // Return URL referencing the stored file logic
                resolve(`/reports/${fileName}`);
            });

            stream.on('error', (err) => {
                reject(err);
            });

        } catch (error) {
            reject(error);
        }
    });
}

module.exports = {
    generateTaxReportPDF
};
